# Generated by Django 2.2.5 on 2019-09-12 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='cpi',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
