# Generated by Django 2.2.5 on 2019-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admet', '0002_click_cpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='cpi',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
