# Generated by Django 2.2.5 on 2019-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admet', '0003_auto_20190912_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='cpi',
            field=models.FloatField(),
        ),
    ]
